### ISSUE TITLE
Add support for viewing the schedule of a group

### ISSUE THREAD

**Issue by gkrol-zermelo** [zermelo-software/zermelo-app#10]
This is not that well supported in the API at this time.

**Comment by Zermelo-Ulbe** [comment]
Version 1.4.0 allows users to view schedules of users, locations and groups by selecting from a list. Users do need permission to view these schedules, obviously.

**Comment by ko3st** [comment]
When can we expect the 1.4 version to be in the Google play store?
 Currently (7th of December 2016) only version  1.3.5 seems to be available.

**Comment by Zermelo-Ulbe** [comment]
I expect we'll start rolling out sometime next week, but a final bit of testing still needs to be done so it could be pushed back. In other words: Soon (tm)
