### ISSUE TITLE
Remove useless files

### ISSUE THREAD

**Issue by gkrol-zermelo** [zermelo-software/zermelo-app#16]
Especially in www/sencha there are a lot of unused files that only increase the size of the app without contributing anything.

**Comment by gkrol-zermelo** [comment]
Mitchell reports that he was able to reduce the size by 10MB by removing the following files:
www/touch/resources/
www/touch/css-debug/
sencha-touch.*.js (debug or alternate versions)
There was also a large file in the "Builds" directory.

Some of these files can be removed, others should probably just be excluded in zip.sh.

**Comment by Zermelo-Ulbe** [comment]
Pre-packaging with Sencha CMD solves these issues
