### ISSUE TITLE
Allow scanning a QR code to link the app

### ISSUE THREAD

**Issue by gkrol-zermelo** [zermelo-software/zermelo-app#19]
It's 2015, why do we have to enter information by hand? Note that this will require the Zermelo Portal to generate the QR code.

**Comment by Nickforall** [comment]
It will be near to impossible to do this using phonegap, it's 2015 use native apps.

**Comment by gkrol-zermelo** [comment]
@Nickforall there are plugins (like this one: http://phonegap.com/blog/build/barcodescanner-plugin/ )

**Comment by mehlon** [comment]
Why not use OAuth2? Simply make the app launch zportal in a mobile browser, let the user log in, then let the site redirect back to the app with an access token.

**Comment by Zermelo-Ulbe** [comment]
This is available since 1.5.0
