### ISSUE TITLE
On some phones, the schedule does not scroll to the current time.

### ISSUE THREAD

**Issue by gkrol-zermelo** [zermelo-software/zermelo-app#2]
The problem has been reported on a Nexus 5 with Android 5.0.1.

**Comment by Thymo-** [comment]
Happens from time to time on my device as well. Oneplus One, Android 5.1.1.

**Comment by Zermelo-Ulbe** [comment]
Scrolling to time has been changed in 1.3.4 and we haven't heard anything about this since then so it's probably fixed.
