### ISSUE TITLE
Scroll balk is incompleet

### ISSUE THREAD

**Issue by milo526** [zermelo-software/zermelo-app#23]
![img_0141](https://cloud.githubusercontent.com/assets/5261909/10914441/c0bfb63a-8252-11e5-8c7f-75a41c8dba30.jpg)

Wanneer er gescrolld wordt in de rooster weergaven (zie bijgevoegd screenshot) mist het bovenste deel van de balk. De afgeronde bovenkant lijkt hierdoor te hoog te zitten.

**Comment by gkrol-zermelo** [comment]
Op iOS zo te zien? Welke versie?

**Comment by milo526** [comment]
Bug wordt geconstateerd op iOS 9.0 t/m 9.2 iPhone & iPad.
Zermelo versie 1.1.4

**Comment by milo526** [comment]
I'm gonna assume this is either already fixed or is not gonna fix; either way I'm going to close this issue to get this out of my issue list 😄
