### ISSUE TITLE
Show "footprints" of moved lessons

### ISSUE THREAD

**Issue by gkrol-zermelo** [zermelo-software/zermelo-app#24]
In the Zermelo Portal when a lesson is moved a blank "footprint" remains behind. This is useful to see what happened to the lesson you were expecting at that date and time.

**Comment by zdevos** [comment]
In the app you see this (vervallen_les_app), while in the portal you see (vervallen_les_portal) when a less is moved or does not take place.
![vervallen_les_app](https://cloud.githubusercontent.com/assets/15995591/11362984/59a81280-9297-11e5-8773-66107de968bf.png)
![vervallen_les_portal](https://cloud.githubusercontent.com/assets/15995591/11362985/59aba5f8-9297-11e5-9bfe-82b5a86bb3af.png)

**Comment by Zermelo-Ulbe** [comment]
Version 1.3.6 will show the same footprints as the Portal.
