### ISSUE TITLE
When entering the code, a numeric keyboard should be shown

### ISSUE THREAD

**Issue by gkrol-zermelo** [zermelo-software/zermelo-app#5]

**Comment by wvanbreukelen** [comment]
You might want to change the ```xtype: 'textfield'```  to ```xtype: 'numberfield'``` in Login.js on line 126
I will try to add a commit. If I cannot work that out, you might want to test it in your own testing envirorment.

(Extra info: http://www.objis.com/formationextjs/lib/extjs-4.0.0/docs/api/Ext.form.field.Number.html

**Comment by wvanbreukelen** [comment]
Might want to add the following parameters:

```
maxValue. minValue
```
See doc link above

**Comment by gkrol-zermelo** [comment]
We might also want to do keyNavEnabled:false and mouseWheelEnabled:false

About the "cdoe" - the guy who wrote the initial version of the app wasn't such a good speller (as you noticed).

**Comment by wvanbreukelen** [comment]
Oh lol. Sorry but I currently don't have the time to bring up a emulator. I think I can work something out tomorrow morning.

**Comment by gkrol-zermelo** [comment]
There is someone who has the app working as a WebApp (without using Phonegap). I believe he just removed the "phonegap.js" file. This makes testing easier. I don't think he shared his modifications yet. You can also use the Ripple emulator to test.

In my opinion Android emulators suck quite a bit, it's much easier to use your own phone. Just connect it using USB in debug mode. Apps start a lot quicker and run smoother.

**Comment by wvanbreukelen** [comment]
> There is someone who has the app working as a WebApp (without using Phonegap). I believe he just removed the "phonegap.js" file. This makes testing easier. I don't think he shared his modifications yet. You can also use the Ripple emulator to test.

Ok, I will try that out.

> n my opinion Android emulators suck quite a bit, it's much easier to use your own phone. Just connect it using USB in debug mode. Apps start a lot quicker and run smoother.

What should I use then, Apache Cordova?

**Comment by gkrol-zermelo** [comment]
Apache Cordova (or PhoneGap) is the technology used to "wrap" the HTML/JavaScript app and turn it into a mobile phone app. It's used for building the APK or the IPA.

I was talking about the Android emulator that's provided with the Android SDK. That one works ok but not great, a real android phone is much nicer for testing.

**Comment by wvanbreukelen** [comment]
I've got a Samsung Galaxy S4 to test it out and I can confirm it is working properly. I managed to fill in the code out of the portal and the institution name and successfully logged in.
I think the parameters maxValue and minValue are not even needed.

I do not know what keyNavEnabled:false and mouseWheelEnabled:false actually change but like previously said, it is working now.

**Comment by gkrol-zermelo** [comment]
Thanks for testing, I accepted your pull request.
