### ISSUE TITLE
The app should support Windows Phone

### ISSUE THREAD

**Issue by gkrol-zermelo** [zermelo-software/zermelo-app#7]
Note that the app uses WebSQL. We might be able to add a library that adds WebSQL support. Another option may be to switch the app to IndexDB (or whatever it is called). This could also result in speed improvements.

**Comment by Zermelo-Ulbe** [comment]
Sencha Touch provides storage facilities that are backed by HTML5 LocalStorage. We replaced WebSQL with this solution and created a Windows Phone version
